# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            Understanding Homelessness
tagline:          ''
description:      'Website for Data Science for Social Good 2024 "Understanding Homelessness" Project' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2024_understanding_homelessness"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2024_understanding_homelessness/
